services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.compose.api
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: devops-db
    restart: unless-stopped
    env_file:
      - .env.compose.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: