services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.compose.api
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: devops-db
    restart: unless-stopped
    env_file:
      - .env.compose.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devops_starter"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  adminer:
    image: adminer
    container_name: devops-adminer
    restart: unless-stopped
    profiles:
      - tools
    ports:
      - "8080:8080"

volumes:
  postgres_data: